public native class questCharacterManagerVisuals_OverridePlayerCustomizations extends questICharacterManagerVisuals_NodeSubType {
  native let customizationData: array<gameuiForcePlayerCustomizationData>;
}
