public abstract native class AICTreeNodeSingleSharedVarDecoratorDefinition extends AICTreeNodeSharedVarsBaseDecoratorDefinition {
  public native let sharedVarName: LibTreeSharedVarRegistrationName;
}
