public native class animAnimNode_SetDrivenKey_InternalsSetDrivenKeyEntryProviderInline extends animAnimNode_SetDrivenKey_InternalsISetDrivenKeyEntryProvider {
  public native let entries: array<animAnimNode_SetDrivenKey_InternalsEntry>;
}
