public enum ERenderProxyType {
  RPT_None = 0,
  RPT_Mesh = 1,
  RPT_PointLight = 2,
  RPT_SpotLight = 3,
  RPT_AreaLight = 4,
  RPT_Particles = 5,
  RPT_Foliage = 6,
  RPT_SSDecal = 7,
  RPT_VectorField = 8,
  RPT_FogVolume = 9,
  RPT_GI = 10,
  RPT_ReflectionProbe = 11,
  RPT_MorphTargetMesh = 12,
  RPT_LightVolume = 13,
  RPT_DynamicDecalSpawner = 14,
  RPT_AutoSpawner = 15,
  RPT_LightBlocker = 16,
}
