public native struct interopGlobalNodeIDInfo {
  native let globalName: String;
  native let globalNodeIDPath: String;
  native let globalNodeIDHash: Uint64;
  native let globalNameIsAutoGenerated: Bool;
}
