public native struct interopGlobalNodeIDInfo {
  public native let globalName: String;
  public native let globalNodeIDPath: String;
  public native let globalNodeIDHash: Uint64;
  public native let globalNameIsAutoGenerated: Bool;
}
