public enum navNavAreaID {
  Unwalkable = 0,
  Terrain = 1,
  Crouchable = 2,
  Regular = 3,
  Road = 4,
  Pavement = 5,
  Door = 10,
  Ladder = 11,
  Jump = 12,
  Elevator = 14,
  Stairs = 15,
  Drones = 16,
  Exploration = 17,
  CrowdWalkable = 5,
}
