public enum PSODescBlendModeWriteMask {
  MASK_None = 0,
  MASK_R = 1,
  MASK_G = 2,
  MASK_B = 4,
  MASK_A = 8,
  MASK_RG = 3,
  MASK_RB = 5,
  MASK_RA = 9,
  MASK_GB = 6,
  MASK_GA = 10,
  MASK_BA = 12,
  MASK_RGB = 7,
  MASK_RGA = 11,
  MASK_RBA = 13,
  MASK_GBA = 14,
  MASK_RGBA = 15,
}
