public native class questCharacterManagerVisuals_SetBrokenNoseStage extends questICharacterManagerVisuals_NodeSubType {
  public native let brokenNoseStage: gameuiCharacterCustomization_BrokenNoseStage;
}
