public enum scnSceneCategoryTag {
  voiceset = 0,
  mainQuests = 1,
  sideQuests = 2,
  minorQuests = 3,
  otherQuests = 4,
  dialoguesQuests = 5,
  streetOpenWorld = 6,
  vendorsOpenWorld = 7,
  dancefloorsOpenWorld = 8,
  cityOpenWorld = 9,
  chatsOpenWorld = 10,
  otherOpenWorld = 11,
  holocalls = 12,
  other = 13,
}
