public enum workWeaponType {
  Any = 0,
  Ranged = 1,
  OneHandedRanged = 2,
  AssaultRifle = 3,
  Hammer = 8,
  Handgun = 9,
  HeavyMachineGun = 10,
  Katana = 11,
  Knife = 12,
  LightMachineGun = 13,
  LongBlade = 14,
  Melee = 16,
  OneHandedClub = 17,
  PrecisionRifle = 18,
  Revolver = 19,
  Rifle = 20,
  ShortBlade = 21,
  Shotgun = 22,
  ShotgunDual = 23,
  SniperRifle = 24,
  SubmachineGun = 25,
  TwoHandedClub = 27,
}
